BlogProject.WEB/Areas/Admin/Controllers/ArticleController.cs
using BlogProject.DAL.Repositories.Interfaces.Concrete;
using BlogProject.Models.Entities.Concrrete;
using BlogProject.Models.Enums;
using BlogProject.WEB.Areas.Admin.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogProject.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ArticleController : Controller
    {

        private readonly IArticleRepository _articleRepository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IAppUserRepository _appUserRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILikeRepository _likeRepository;
        private readonly ICommentRepository _commentRepository;

        public ArticleController(IArticleRepository articleRepository, UserManager<IdentityUser> userManager, IAppUserRepository appUserRepository, ICategoryRepository categoryRepository, IWebHostEnvironment webHostEnvironment, ILikeRepository likeRepository, ICommentRepository commentRepository)
        {
            _articleRepository = articleRepository;
            _userManager = userManager;
            _appUserRepository = appUserRepository;
            _categoryRepository = categoryRepository;
            _webHostEnvironment = webHostEnvironment; 
            _likeRepository = likeRepository;
            _commentRepository = commentRepository;
        }
        // List
        public async Task<IActionResult> List()
        {

            var articleList = _articleRepository.GetByDefaults
                (
               
                selector: a => new GetArticleVM()
                {
                    ArticleID = a.ID,
                    CategoryName = a.Category.Name, 
                    Title = a.Title,
                    Content = a.Content,
                    Image = a.Image,
                    UserFullName = a.AppUser.FullName 
                },
              
                expression: a => a.Statu != Statu.Passive,
              
                include: a => a.Include(a => a.AppUser).Include(a => a.Category),
              
                orderby: a => a.OrderByDescending(a => a.CreateDate)
                );

            return View(articleList);
        }

        // Detail
        public async Task<IActionResult> Detail(int id)
        {
          
            ArticleDetailVM articleDetailVM = new ArticleDetailVM()
            {
                Article = _articleRepository.GetDefault(a => a.ID == id),

            };
                   
            articleDetailVM.Article.Category = _categoryRepository.GetDefault(a => a.ID == articleDetailVM.Article.CategoryID);
                       
            articleDetailVM.Article.AppUser = _appUserRepository.GetDefault(a => a.ID == articleDetailVM.Article.AppUserID);
                     
            articleDetailVM.userFollowedCategories = _categoryRepository.GetCategoryWithUser(articleDetailVM.Article.AppUser.ID);

            articleDetailVM.Mail = _userManager.Users.FirstOrDefault(a => a.Id == articleDetailVM.Article.AppUser.IdentityId).Email;
                       
            articleDetailVM.Article.Likes = _likeRepository.GetLikes(a => a.ArticleID == articleDetailVM.Article.ID);

            
            articleDetailVM.Article.Comments = _commentRepository.GetDefaults(a => a.ArticleID == articleDetailVM.Article.ID && a.Statu != Statu.Passive);

            foreach (var item in articleDetailVM.Article.Comments)
            {
                item.AppUser = _appUserRepository.GetDefault(a => a.ID == item.AppUserID);
            }
                       
            IdentityUser identityUser = await _userManager.GetUserAsync(User);
            articleDetailVM.ActiveAppUser = _appUserRepository.GetDefault(a => a.IdentityId == identityUser.Id);

            articleDetailVM.ActiveArticleID = id;

            _articleRepository.Read(articleDetailVM.Article);

            return View(articleDetailVM);
        }

        // Delete
        public IActionResult Delete(int id)
        {
            Article article = _articleRepository.GetDefault(a => a.ID == id);
            _articleRepository.Delete(article);
            return RedirectToAction("Index", "AppUser");
        }

        // Like
        public async Task<IActionResult> Like(int id)
        {
            Article article = _articleRepository.GetDefault(a => a.ID == id);

            IdentityUser identityUser = await _userManager.GetUserAsync(User);

            AppUser appUser = _appUserRepository.GetDefault(a => a.IdentityId == identityUser.Id);


            Like like = new Like()
            {
                AppUser = appUser,
                AppUserID = appUser.ID,
                Article = article,
                ArticleID = article.ID
            };

            _likeRepository.Create(like);

            return RedirectToAction("Detail", new
            {
                id = id
            });
        }

        // Unlike
        public async Task<IActionResult> Unlike(int id)
        {
            Article article = _articleRepository.GetDefault(a => a.ID == id);

            IdentityUser identityUser = await _userManager.GetUserAsync(User);

            AppUser appUser = _appUserRepository.GetDefault(a => a.IdentityId == identityUser.Id);

            Like like = _likeRepository.GetDefault(a => a.ArticleID == article.ID && a.AppUserID == appUser.ID);

            _likeRepository.Delete(like);
            return RedirectToAction("Detail", new { id = id });
        }

        // ListArticle Of Category
        public IActionResult ListWithFilter(int id)
        {
            List<GetArticleWithUserVM> articles = _articleRepository.GetByDefaults
                (
                    selector: a => new GetArticleWithUserVM()
                    {
                        Title = a.Title,
                        Content = a.Content,
                        UserId = a.AppUser.ID, 
                        UserFullName = a.AppUser.FullName, 
                        UserImage = a.AppUser.Image,
                        ArticleId = a.ID,
                        Image = a.Image,
                        CreatedDate = a.CreateDate,
                        CategoryName = a.Category.Name, 
                        CategoryID = a.CategoryID,
                        ReadingTime = a.ReadingTime,
                        CreateDate = a.CreateDate,
                        ReadCounter = a.ReadCounter
                    },
                  
                    expression: a => a.Statu != Statu.Passive && a.CategoryID == id,
                 
                    include: a => a.Include(a => a.AppUser).Include(a => a.Category),
                  
                    orderby: a => a.OrderByDescending(a => a.CreateDate)
                );
           
            ViewBag.AllCategory = _categoryRepository.GetDefaults(a => a.Statu != Statu.Passive);
            return View(articles);
        }

        // ListWithFilters
        public IActionResult ListWithFilters(List<int> categories)
        {
            if (categories.Count == 0)
            {
                return RedirectToAction("Index", "AppUser");
            }
            List<GetArticleWithUserVM> articles = _articleRepository.GetByDefaults
                 (
               
                selector: a => new GetArticleWithUserVM()
                {
                    Title = a.Title,
                    Content = a.Content,
                    UserId = a.AppUser.ID, 
                    UserFullName = a.AppUser.FullName, 
                    UserImage = a.AppUser.Image,
                    ArticleId = a.ID,
                    Image = a.Image,
                    CreatedDate = a.CreateDate,
                    CategoryName = a.Category.Name, 
                    CategoryID = a.CategoryID,
                    ReadingTime = a.ReadingTime,
                    CreateDate = a.CreateDate,
                    ReadCounter = a.ReadCounter
                },
      
        expression: a => a.Statu != Statu.Passive,
  
        include: a => a.Include(a => a.AppUser).Include(a => a.Category),
     
        orderby: a => a.OrderByDescending(a => a.CreateDate)
                 );

            var newArticleList = articles.Where(article => categories.Contains(article.CategoryID)).ToList();

            ViewBag.AllCategory = _categoryRepository.GetDefaults(a => a.Statu != Statu.Passive);

            return View(newArticleList);

        }

        // Checklist
        public IActionResult Checklist()
        {
            var articleList = _articleRepository.GetByDefaults
                 (
              
                 selector: a => new GetArticleVM()
                 {
                     ArticleID = a.ID,
                     CategoryName = a.Category.Name, 
                     Title = a.Title,
                     Content = a.Content,
                     Image = a.Image,
                     UserFullName = a.AppUser.FullName 
                 },
               
                 expression: a => a.Statu == Statu.Passive && a.AdminCheck == AdminCheck.Waiting,
               
                 include: a => a.Include(a => a.AppUser).Include(a => a.Category),
             
                 orderby: a => a.OrderByDescending(a => a.CreateDate)
                 );
            return View(articleList);
        }

        // Approve
        public IActionResult Approve(int id)
        {
            Article article = _articleRepository.GetDefault(a => a.ID == id);
            _articleRepository.Approve(article);
            return RedirectToAction("Checklist");
        }

        // Reject
        public IActionResult Reject(int id)
        {
            Article article = _articleRepository.GetDefault(a => a.ID == id);

BlogProject.WEB/Controllers/UserController.cs
using AutoMapper;
using BlogProject.DAL.Repositories.Interfaces.Concrete;
using BlogProject.Models.Entities.Concrrete;
using BlogProject.Models.Enums;
using BlogProject.WEB.Models.DTOs;
using BlogProject.WEB.Models.VMs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace BlogProject.WEB.Controllers
{
    public class UserController : Controller
    {
        private readonly IAppUserRepository _appUserRepository;
        private readonly UserManager<IdentityUser> _userManager; 
        private readonly IMapper _mapper; 
        private readonly IArticleRepository _articleRepository;
        private readonly ICategoryRepository _categoryRepository;

        public UserController(IAppUserRepository appUserRepository, UserManager<IdentityUser> userManager, IMapper mapper, IArticleRepository articleRepository, ICategoryRepository categoryRepository)
        {
            _appUserRepository = appUserRepository; 
            _userManager = userManager; 
            _mapper = mapper;
            _articleRepository = articleRepository;
            _categoryRepository = categoryRepository;
        }

        // Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
       
        public async Task<IActionResult> Create(CreateUserDTO createUserDTO)
        {
            if (ModelState.IsValid)
            {
             
                var checkUserName = _userManager.Users.Any(a => a.UserName == createUserDTO.UserName);
                var checkMail = _userManager.Users.Any(a => a.Email == createUserDTO.Mail);

                if (!checkMail && !checkUserName) 
                {                   
                    string newId = Guid.NewGuid().ToString();
                    IdentityUser identityUser = new IdentityUser()
                    {
                        Email = createUserDTO.Mail,
                        UserName = createUserDTO.UserName,
                        Id = newId
                    };

                    IdentityResult result = await _userManager.CreateAsync(identityUser, createUserDTO.Password);
                    if (result.Succeeded)
                    {
                        await _userManager.AddToRoleAsync(identityUser, "Member");

                        var user = _mapper.Map<AppUser>(createUserDTO);

                        user.IdentityId = newId;

                        if (createUserDTO.ImagePath != null)
                        {
                        
                            using var image = Image.Load(createUserDTO.ImagePath.OpenReadStream());
                            image.Mutate(a => a.Resize(500, 500)); 
                            image.Save($"wwwroot/images/users/{user.UserName}.jpg");
                          
                            user.Image = ($"/images/users/{user.UserName}.jpg");

                            _appUserRepository.Create(user);
                            return RedirectToAction("Login", "Home"); 
                        }
                    }
                }
                else
                {
                  
                    TempData["Message"] = "Bu mail adresi veya kullanıcı adı daha önce alınmıştır.";
                }
            }
            return View(createUserDTO); 
        }

        // Detail ArticleList Of User
        public async Task<IActionResult> Detail(int id)
        {
            AppUser appUser = _appUserRepository.GetDefault(a => a.ID == id);
            IdentityUser identityUser = await _userManager.FindByIdAsync(appUser.IdentityId);

            List<Article> articleList = _articleRepository.GetDefaults(a => a.Statu != Statu.Passive && a.AppUserID == appUser.ID);

            List<Category> userFollowedCategories = _categoryRepository.GetCategoryWithUser(appUser.ID);

            GetProfileVM getProfileVM = new GetProfileVM()
            {
                FullName = appUser.FullName,
                Image = appUser.Image,
                Mail = identityUser.Email,
                Articles = articleList,
                Categories = userFollowedCategories,
            };
          
            foreach (var item in getProfileVM.Articles)
            {
                item.Category = _categoryRepository.GetDefault(a => a.Statu != Statu.Passive && a.ID == item.CategoryID);
            }

            return View(getProfileVM);
        }
    }
}

BlogProject.WEB/Views/Shared/Components/Articles/ArticlesViewComponent.cs
using BlogProject.DAL.Repositories.Interfaces.Concrete;
using BlogProject.Models.Enums;
using BlogProject.WEB.Models.VMs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogProject.WEB.Views.Shared.Components.Articles
{
    [ViewComponent(Name = "Articles")] // Articles isminde bir ViewComponent olduğunu söyledik
    public class ArticlesViewComponent : ViewComponent // Bu sınıfın bir ViewComponent olduğunu ViewComponent sınıfından kalıtım alarak söyleriz.
    {
        // Oluşma tarihine göre güncel 10 makale gösterilecektir.
        private readonly IArticleRepository _articleRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ArticlesViewComponent(IArticleRepository articleRepository,ICategoryRepository categoryRepository)
        {
            _articleRepository = articleRepository;
            _categoryRepository = categoryRepository;
        }
        public IViewComponentResult Invoke()
        {
            List<GetArticleWithUserVM> articles = _articleRepository.GetByDefaults
                (
                    // Selector parametresi ile yeni bir GetArticleWithUserVM tipinde yeni bir nesne oluşturacağımız söylenir.
                    selector: a => new GetArticleWithUserVM()
                    {
                        Title = a.Title,
                        Content = a.Content,
                        UserId = a.AppUser.ID, // AppUser tablosu ile include edilip alınacak veri
                        UserFullName = a.AppUser.FullName, // AppUser tablosu ile include edilip alınacak veri
                        UserImage = a.AppUser.Image,  
                        ArticleId = a.ID,
                        Image = a.Image,
                        CreatedDate = a.CreateDate,
                        CategoryName = a.Category.Name, // Category tablosu ile include edilip alınacak veri
                        CategoryID=a.CategoryID,
                        ReadingTime=a.ReadingTime,
                        CreateDate=a.CreateDate,
                        ReadCounter=a.ReadCounter
                    },
                    // Expression parametresi ile Statu su passive olmayan  koşulu söylenir
                    expression: a => a.Statu !=  Statu.Passive,
                    // Article tablosu ile AppUser ve Category tablosunun birleştirildiği söylenir.
                    include: a=>a.Include(a=>a.AppUser).Include(a=>a.Category),
                    // Sıralarken son oluşturulma tarihinden itibaren sırala dedik
                    orderby: a=>a.OrderByDescending(a=>a.CreateDate)
                );
            // Oluşturulan bu articles nesnesinin 10 adedini al. Take metodu kullanıldığı için tekrardan ToList() metodu kullanılmak zorundadır.
            ViewBag.AllCategory = _categoryRepository.GetDefaults(a=>a.Statu!=Statu.Passive);
            return View(articles.Take(10).ToList());
        }
    }
}

BlogProject.WEB/Views/Article/Detail.cshtml
@model ArticleDetailVM

<div class="row mt-2">

    <div class="col-md-9">
        <hr />

        <!-- Irformation Header -->
        <div class="row mt-2">

            <!-- Writer Profile Pic-->
            <div class="col-md-1 px-0 ms-2 p-0">
                <img class="rounded-circle p-0" src="@Model.Article.AppUser.Image" style="height:75px;width:65px" />
            </div>

            <!-- Information Detail -->
            <div class="col-md-10 ">
                <!-- Writer FullName -->
                <div class="">
                    <a class="text-dark fw-bold" asp-controller="User" asp-action="Detail" asp-route-id="@Model.Article.AppUser.ID">@Model.Article.AppUser.FullName</a>
                </div>

                <!-- CreateDate - Reading Time -->
                <div class="">
                    <label class="text-muted fw-light">@Model.Article.CreateDate.ToShortDateString() / @Model.Article.ReadingTime min read / @Model.Article.ReadCounter times read </label>
                </div>

                <!-- Category -->
                <div class="">
                    <a asp-action="DetailWithFilter" asp-controller="Article" asp-route-id="@Model.Article.CategoryID" class="btn btn-secondary btn-sm fw-info px-2 py-1">@Model.Article.Category.Name</a>
                </div>

            </div>

        </div>

        <!--Article -->
        <div>
            <div class="row">
                <!-- Article Title - Content -->
                <div class="col-md-12 pe-2">

                    <h5 class="mt-2 fw-bold"><strong>@Model.Article.Title</strong></h5>

                    <div class="d-flex justify-content-center mt-3">

                        <img class="mt-3" src="@Model.Article.Image" style="height:400px;width:800px; object-fit:fill" />

                    </div>

                    <p class="mb-1 mt-5">
                        @Model.Article.Content
                    </p>

                </div>

            </div>
        </div>
        <!-- Like Comment -->
        <div>

            <!-- Like -->
            <div class="mt-3">

                <i class="fa fa-heart-o me-1" aria-hidden="true" style="color:red"></i>
                <label>@Model.Article.Likes.Count()</label>

            </div>

            <!-- Comments -->

            <div class="mt-4">

                @foreach (var item in @Model.Article.Comments.OrderByDescending(a => a.CreateDate))
                {
                    <hr />

                    <div class="row mt-2">
                        <!-- Comment Writer Image -->
                    <div class="col-md-1 px-0 ms-2 p-0">
                            <img class="rounded-circle p-0" src="@item.AppUser.Image" style="height:50px;width:50px" />
                        </div>
                        <!-- Information Detail -->
                    <div class="col-md-10 ">
                            <!-- Comment Writer FullName -->

                        <div class="">
                                <a class="text-dark fw-bold" asp-controller="User" asp-action="Detail" asp-route-id="@item.AppUserID">@item.AppUser.FullName</a>
                            </div>

                            <!-- CreateDate -->
                        <div class="">
                                <label class="text-muted fw-light">@item.CreateDate.ToShortDateString() </label>
                            </div>

                        </div>
                    </div>

                    <!-- Comment Text -->
                    <p class="mt-2">@item.Text</p> 
                } 
            </div>

        </div>
        <hr />

    </div>

    <!-- Followed Category and Information Of Writer -->
    <div class="col-md-2 ms-5" style="border-left: medium solid grey">
        <div class="row sticky-top ms-3">
            <div class="mt-4">
                <div>
                    <img class="rounded-circle" src="@Model.Article.AppUser.Image" style="height:100px;width:100px" />
                </div>

                <h6 class="mt-4 fw-bold">@Model.Article.AppUser.FullName</h6>
                <p class="text-muted fw-normal fst-italic">@Model.Mail</p>

                <p class="mt-4 p-0 fw-bold" style="border-bottom: thin solid grey">Following Categories</p>


                @foreach (var item in @Model.userFollowedCategories)
                {
                    <div class="mb-2">
                        <a class="mb-2 text-dark " asp-controller="Article" asp-action="ListWithFilter" asp-route-id="@item.ID">@item.Name</a>
                    </div>
                }

            </div>

        </div>

    </div>
</div>

BlogProject.WEB/Views/Article/ListWithFilter.cshtml
@model List<GetArticleWithUserVM>


<div class="row mt-2">

    <!-- AppUser Article List -->
    <div class="col-md-9">
        <hr />
        @foreach (var item in @Model)
        {
            <!-- Irformation Header -->
            <div class="row mt-2">

                <!-- Writer Profile Pic-->
            <div class="col-md-1 px-0 ms-2 p-0">
                    <img class="rounded-circle p-0" src="@item.UserImage" style="height:55px;width:50px" />
                </div>

                <!-- Information Detail -->
            <div class="col-md-10">
                    <!-- Writer FullName -->
                <div class="">
                        <a class="text-dark fw-bold" asp-controller="User" asp-action="Detail" asp-route-id="@item.UserId">@item.UserFullName </a>
                    </div>
                    <!--Create Date - Reading Time-->
                <div>
                        <label class="text-muted fw-light">@item.CreateDate.ToShortDateString() / @item.ReadingTime - min read / @item.ReadCounter times read</label>
                    </div>
                </div>

            </div>
            <!--Article List-->
            <div>
                <div class="row">
                    <!-- Article Title - Content -->
                <div class="col-md-9 pe-2">

                        @if (@item.Title.Length > 100)
                        {
                            <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ArticleId" class="fw-bold text-dark">
                                <h5 class="mt-2"><strong>@item.Title.Substring(0,100)</strong></h5>
                            </a>
                        }
                        else
                        {
                            <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ArticleId" class="fw-bold text-dark">
                                <h5 class="mt-2"><strong>@item.Title</strong></h5>
                            </a>

                        }


                        @if (@item.Content.Length > 250)
                        {
                            <p class="mb-1">
                                @item.Content.Substring(0,250) <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ArticleId" class="fw-bold">...</a>
                            </p>
                        }
                        else
                        {
                            <p class="mb-1">
                                @item.Content
                            </p>
                        }

                        <!--Article Category-->

                    <a asp-action="ListWithFilter" asp-controller="Article" asp-route-id="@item.CategoryID" class="btn btn-secondary btn-sm fw-info px-2 py-1">@item.CategoryName</a>


                    </div>

                    <!-- Article Image -->
                <div class="col-md-2 d-flex justify-content-end">

                        <img class="mt-3" src="@item.Image" style="height:120px;width:120px" />

                    </div>
                </div>
            </div>
            <hr />
        }

    </div>

    <!-- Followed Category and Information Div -->
    <div class="col-md-2 ms-5" style="border-left: medium solid grey">
        <div class="row sticky-top ms-3">
            <div class="mt-4">


                <p class="mt-4 p-0 fw-bold" style="border-bottom: thin solid grey">Followable Categories</p>

                <form asp-controller="Article" asp-action="ListWithFilters" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="All"></div>
                    <div class="mb-2">
                        <button type="submit" class="btn btn-success">Filters</button>
                        <hr />
                    </div>

                    @foreach (var item in @ViewBag.AllCategory)
                    {
                        if ((Model as IEnumerable<GetArticleWithUserVM>).Any(a => a.CategoryID == @item.ID))
                        {
                            <div class="mb-2">
                                <input type="checkbox" class="btn-check" name="categories[]" value="@item.ID" id="@item.ID" autocomplete="off" checked>
                                <label class="btn btn-outline-primary" for="@item.ID">@item.Name</label>
                                <br>
                            </div>

                        }
                        else
                        {
                            <div class="mb-2">
                                <input type="checkbox" class="btn-check" name="categories[]" value="@item.ID" id="@item.ID" autocomplete="off">
                                <label class="btn btn-outline-primary" for="@item.ID">@item.Name</label>
                                <br>
                            </div>
                        }

                    }
                </form>


            </div>

        </div>

    </div>
</div>