BlogProject.WEB/Areas/Admin/Controllers/AppUserController.cs
using BlogProject.DAL.Repositories.Interfaces.Concrete;
using BlogProject.Models.Entities.Concrrete;
using BlogProject.Models.Enums;
using BlogProject.WEB.Areas.Admin.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogProject.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")] 
    public class AppUserController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IAppUserRepository _appUserRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IArticleRepository _articleRepository;
        private readonly ICategoryRepository _categoryRepository;

        public AppUserController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, IAppUserRepository appUserRepository, IWebHostEnvironment webHostEnvironment, IArticleRepository articleRepository, ICategoryRepository categoryRepository)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _appUserRepository = appUserRepository;
            _webHostEnvironment = webHostEnvironment;
            _articleRepository = articleRepository;
            _categoryRepository = categoryRepository;
        }

        // Index HomePage
        public IActionResult Index()
        {
            List<GetArticleWithUserVM> articles = _articleRepository.GetByDefaults
           (
               
                selector: a => new GetArticleWithUserVM()
                {
                    Title = a.Title,
                    Content = a.Content,
                    UserId = a.AppUser.ID, 
                    UserFullName = a.AppUser.FullName, 
                    UserImage = a.AppUser.Image,
                    ArticleId = a.ID,
                    Image = a.Image,
                    CreatedDate = a.CreateDate,
                    CategoryName = a.Category.Name, 
                    CategoryID = a.CategoryID,
                    ReadingTime = a.ReadingTime,
                    CreateDate = a.CreateDate,
                    ReadCounter = a.ReadCounter
                },
                  
                    expression: a => a.Statu != Statu.Passive,
                
                    include: a => a.Include(a => a.AppUser).Include(a => a.Category),
              
                    orderby: a => a.OrderByDescending(a => a.CreateDate)
             );
           
            ViewBag.AllCategory = _categoryRepository.GetDefaults(a => a.Statu != Statu.Passive);
            return View(articles.Take(10).ToList());
        }

        // List
        public IActionResult List()
        {
            List<AppUser> appUsers = _appUserRepository.GetDefaults(a => a.Statu != Statu.Passive);
            ViewBag.MailList = _userManager.Users.ToList();
            return View(appUsers);
        }

        // Delete
        public async Task<IActionResult> Delete(int id)
        {
            AppUser appUser = _appUserRepository.GetDefault(a=>a.ID==id);
            IdentityUser identityUser = await _userManager.FindByIdAsync(appUser.IdentityId); ;            
            _appUserRepository.Delete(appUser);
            return RedirectToAction("List");
        }

        // LogOut
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return Redirect("~/");
        }

        // Detail
        public async Task<IActionResult> Detail(int id)
        {

            AppUser appUser = _appUserRepository.GetDefault(a => a.ID == id);
            IdentityUser identityUser = await _userManager.FindByIdAsync(appUser.IdentityId);

            List<Article> articleList = _articleRepository.GetDefaults(a => a.Statu != Statu.Passive && a.AppUserID == appUser.ID);

            List<Category> userFollowedCategories = _categoryRepository.GetCategoryWithUser(appUser.ID);

            GetAppUserProfileVM getProfileVM = new GetAppUserProfileVM()
            {
                FullName = appUser.FullName,
                Image = appUser.Image,
                Mail = identityUser.Email,
                Articles = articleList,
                Categories = userFollowedCategories,
            };

           
            foreach (var item in getProfileVM.Articles)
            {
                item.Category = _categoryRepository.GetDefault(a => a.Statu != Statu.Passive && a.ID == item.CategoryID);
            }


            return View(getProfileVM);
        }

        // CheckList
        public IActionResult Checklist()
        {
            List<AppUser> appUsers = _appUserRepository.GetDefaults(a => a.AdminCheck==AdminCheck.Waiting && a.Statu==Statu.Passive);
            ViewBag.MailList = _userManager.Users.ToList();
            return View(appUsers);
        }

        // Approve
        public IActionResult Approve(int id)
        {
            AppUser appUser = _appUserRepository.GetDefault(a=>a.ID== id);
            _appUserRepository.Approve(appUser);
            return RedirectToAction("Checklist");
        }

        // Approve
        public IActionResult Reject(int id)
        {
            AppUser appUser = _appUserRepository.GetDefault(a => a.ID == id);
            _appUserRepository.Reject(appUser);
            return RedirectToAction("Checklist");
        }

    }
}

BlogProject.WEB/Controllers/ArticleController.cs
using BlogProject.DAL.Repositories.Interfaces.Concrete;
using BlogProject.Models.Entities.Concrrete;
using BlogProject.Models.Enums;
using BlogProject.WEB.Models.VMs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogProject.WEB.Controllers
{
    public class ArticleController : Controller
    {

        private readonly IArticleRepository _articleRepository;
        private readonly ILikeRepository _likeRepository;
        private readonly ICommentRepository _commentRepository;
        private readonly IAppUserRepository _appUserRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly UserManager<IdentityUser> _userManager;

        public ArticleController(IArticleRepository articleRepository, ILikeRepository likeRepository, ICommentRepository commentRepository, IAppUserRepository appUserRepository, UserManager<IdentityUser> userManager, ICategoryRepository categoryRepository)
        {
            _articleRepository = articleRepository;
            _likeRepository = likeRepository;
            _commentRepository = commentRepository;
            _appUserRepository = appUserRepository;
            _userManager = userManager;
            _categoryRepository = categoryRepository;
        }

        // Detail 
        public IActionResult Detail(int id)
        {
            ArticleDetailVM articleDetailVM = new ArticleDetailVM()
            {
                Article = _articleRepository.GetDefault(a => a.ID == id)

            };

            articleDetailVM.Article.Category = _categoryRepository.GetDefault(a => a.ID == articleDetailVM.Article.CategoryID);

            articleDetailVM.Article.AppUser = _appUserRepository.GetDefault(a => a.ID == articleDetailVM.Article.AppUserID);

            articleDetailVM.userFollowedCategories = _categoryRepository.GetCategoryWithUser(articleDetailVM.Article.AppUser.ID);

            articleDetailVM.Mail = _userManager.Users.FirstOrDefault(a => a.Id == articleDetailVM.Article.AppUser.IdentityId).Email;

            articleDetailVM.Article.Likes = _likeRepository.GetLikes(a => a.ArticleID == articleDetailVM.Article.ID);

            articleDetailVM.Article.Comments = _commentRepository.GetDefaults(a => a.ArticleID == articleDetailVM.Article.ID && a.Statu != Statu.Passive);

            foreach (var item in articleDetailVM.Article.Comments)
            {
                item.AppUser = _appUserRepository.GetDefault(a => a.ID == item.AppUserID);
            }

 _articleRepository.Read(articleDetailVM.Article);

            return View(articleDetailVM);
        }

        public IActionResult ListWithFilter(int id)
        {
            List<GetArticleWithUserVM> articles = _articleRepository.GetByDefaults
                (
                    selector: a => new GetArticleWithUserVM()
                    {
                        Title = a.Title,
                        Content = a.Content,
                        UserId = a.AppUser.ID, 
                        UserFullName = a.AppUser.FullName, 
                        UserImage = a.AppUser.Image,
                        ArticleId = a.ID,
                        Image = a.Image,
                        CreatedDate = a.CreateDate,
                        CategoryName = a.Category.Name, 
                        CategoryID = a.CategoryID,
                        ReadingTime = a.ReadingTime,
                        CreateDate = a.CreateDate,
                        ReadCounter = a.ReadCounter
                    },
                  
                    expression: a => a.Statu != Statu.Passive && a.CategoryID == id,
                
                    include: a => a.Include(a => a.AppUser).Include(a => a.Category),
                 
                    orderby: a => a.OrderByDescending(a => a.CreateDate)
                );
           
            ViewBag.AllCategory = _categoryRepository.GetDefaults(a => a.Statu != Statu.Passive);
            return View(articles);
        }

        // ListWithFilters
        public IActionResult ListWithFilters(List<int> categories)
        {
            if (categories.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GetArticleWithUserVM> articles = _articleRepository.GetByDefaults
                 (
               
                selector: a => new GetArticleWithUserVM()
                {
                    Title = a.Title,
                    Content = a.Content,
                    UserId = a.AppUser.ID, 
                    UserFullName = a.AppUser.FullName,
                    UserImage = a.AppUser.Image,
                    ArticleId = a.ID,
                    Image = a.Image,
                    CreatedDate = a.CreateDate,
                    CategoryName = a.Category.Name, 
                    CategoryID = a.CategoryID,
                    ReadingTime = a.ReadingTime,
                    CreateDate = a.CreateDate,
                    ReadCounter = a.ReadCounter,
                },
       
        expression: a => a.Statu != Statu.Passive,
     
        include: a => a.Include(a => a.AppUser).Include(a => a.Category),

        orderby: a => a.OrderByDescending(a => a.CreateDate)
                 );

            var newArticleList = articles.Where(article => categories.Contains(article.CategoryID)).ToList();

            ViewBag.AllCategory = _categoryRepository.GetDefaults(a => a.Statu != Statu.Passive);

            return View(newArticleList);
        }
    }
}

BlogProject.WEB/Areas/Admin/Views/AppUser/About.cshtml
<div class="container-fluid">
    <div class="row">
        <h3>ABOUT</h3>
    </div>
    <div class="row">

        <img src="~/images/aboutus.jpg" />
        <p>
            Suspendisse eget lectus luctus, accumsan neque vel, pellentesque metus. Donec quis luctus justo, ultricies lobortis ante. Phasellus sodales elit non convallis scelerisque. Curabitur ac eleifend lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas elementum, turpis vitae dictum luctus, elit arcu malesuada ex, nec scelerisque tortor ipsum id eros. In sit amet felis vel magna faucibus tristique. Etiam id elit nisl. Praesent ac velit in augue pellentesque lobortis id a magna. Vestibulum pellentesque venenatis sem, sed facilisis diam hendrerit pellentesque. Cras lobortis ac nulla a tempor. Sed maximus nulla ut pretium egestas. Phasellus ut tristique ex. Cras urna leo, tempus id vulputate ut, sodales ac erat.
        </p>
    </div>

    <div class="row mt-2" style="border-color:crimson;border:solid;">

        <div>
            <h2>Contact</h2>
        </div>
        <div>
            <p>You can contact me in many ways. feel free to contact me</p>
            <hr style="color:crimson" />
        </div>

        <div class="info row mt-2">
            <div class="col-md-6">

                <div class=row>
                    <div class="col-md-2">
                        <i class="fa fa-globe fa-3x"></i>
                    </div>
                    <div class="col-md-10">
                        <h4>Location:</h4>
                        <p>Kucukcekmece, Istanbul, TURKEY</p>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-2">
                        <i class="fa fa-envelope fa-3x"></i>
                    </div>

                    <div class="col-md-10">
                        <h4>Email:</h4>
                        <p>hasanutebay@gmail.com</p>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-2">
                        <i class="fa fa-mobile fa-3x"></i>
                    </div>

                    <div class="col-md-10">
                        <h4>Call:</h4>
                        <p>+90 507 169 27 95</p>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-2">
                        <i class="fa fa-whatsapp fa-3x"></i>
                    </div>
                    <div class="col-md-10">
                        <h4>Message:</h4>
                        <p>+90 507 169 27 95</p>
                    </div>
                </div>

            </div>


            <div class="col-md-6">

                <iframe src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=Ye%C5%9Filova,%20%C3%96%C4%9Fretmenler%20Sk.%20No:11,%2034295%20K%C3%BC%C3%A7%C3%BCk%C3%A7ekmece/%C4%B0stanbul+(My%20Business%20Name)&amp;t=&amp;z=15&amp;ie=UTF8&amp;iwloc=B&amp;output=embed" frameborder="0" style="border:0; width: 100%; height: 310px;" allowfullscreen=""></iframe>


            </div>

        </div>

    </div>

    <div>
        <form asp-action="" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            <div class="card-body">
                <!-- FirstName -->
                <div class="form-group">
                    <label>Full Name</label>
                    <input type="text" class="form-control">
                </div>
                <!-- Mail -->
                <div class="form-group">
                    <label>E-Mail</label>
                    <input type="email" class="form-control">
                </div>
                <!-- Subject -->
                <div class="form-group">
                    <label>Subject</label>
                    <input type="text" class="form-control">
                </div>
                <!-- Content -->
                <div class="form-group">
                    <label>Content</label>
                    <textarea rows="10" style="resize:none;width:100%;"></textarea>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Send</button>
            </div>
        </form>
    </div>

</div>

BlogProject.WEB/Areas/Admin/Views/AppUser/ActivatedUserDetail.cshtml
@model GetAppUserProfileVM


<div class="row mt-2">

    <!-- AppUser Article List -->
    <div class="col-md-9">
        <hr />
        @foreach (var item in @Model.Articles.OrderByDescending(a=>a.CreateDate))
        {
            <!--Article List-->
            <div>
                <div class="row">
                    <!-- Article Title - Content -->
                <div class="col-md-10 pe-2">

                        @if (@item.Title.Length > 100)
                        {
                            <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ID" class="fw-bold text-dark">
                                <h5 class="mt-2"><strong>@item.Title.Substring(0,100)</strong></h5>
                            </a>
                        }
                        else
                        {
                            <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ID" class="fw-bold text-dark">
                                <h5 class="mt-2"><strong>@item.Title</strong></h5>
                            </a>

                        }


                        @if (@item.Content.Length > 250)
                        {
                            <p class="mb-1">
                                @item.Content.Substring(0,250) <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ID" class="fw-bold">...</a>
                            </p>
                        }
                        else
                        {
                            <p class="mb-1">
                                @item.Content
                            </p>
                        }

                        <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.CategoryID" class="btn btn-secondary btn-sm fw-info px-2 py-1">@item.Category.Name</a>

                        <label class="m-2 text-muted fw-light"> @item.ReadingTime - min read - @item.CreateDate.ToShortDateString()</label>

                    </div>

                    <!-- Article Image -->
                <div class="col-md-2 d-flex justify-content-end">

                        <img class="mt-3" src="@item.Image" style="height:120px;width:120px" />

                    </div>
                </div>
            </div>
            <hr />
        }

    </div>

    <!-- Followed Category and Information Div -->
    <div class="col-md-2 ms-5" style="border-left: medium solid grey">
        <div class="row sticky-top ms-3">
            <div class="mt-4">
                <div>
                    <img class="rounded-circle" src="@Model.Image" style="height:100px;width:100px" />
                </div>

                <h6 class="mt-4 fw-bold">@Model.FullName</h6>
                <p class="text-muted fw-normal fst-italic">@Model.Mail</p>

                <p class="mt-4 p-0 fw-bold" style="border-bottom: thin solid grey">Following Categories</p>


                @foreach (var item in @Model.Categories)
                {
                    <div class="mb-2">
                        <a class="mb-2 text-dark " asp-action="Detail" asp-route-id="@item.ID" >@item.Name</a>
                    </div>
                }


            </div>
            <!-- Profile Picture -->


        </div>

    </div>
</div>

BlogProject.WEB/Areas/Admin/Views/AppUser/Checklist.cshtml
@model List<AppUser>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Users</h3>
        <div class="card-tools">
            <ul class="pagination pagination-sm float-right">
                <li class="page-item"><a class="page-link" href="#">«</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">»</a></li>
            </ul>
        </div>
    </div>

    <div class="card-body p-0">
        <table class="table">

            <!-- Table Head -->
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>FullName</th>
                    <th>UserName</th>
                    <th>E-Mail</th>
                    <th>Password</th>
                    <th style="width: 200px" class="text-center">Operations</th>
                </tr>
            </thead>

            <!-- Table Body -->
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><img src="@item.Image" class="img-circle" style="width: 50px" /></td>
                  <td> <a class="text-dark" asp-controller="AppUser" asp-action="Detail" asp-route-id="@item.ID">@item.FullName</a></td>
                        <td>@item.UserName</td>
                        <td>
                            @foreach (var users in ViewBag.MailList)
                            {
                                @if (users.Id==item.IdentityId)
                                {
                                    @users.Email
                                }
                            }
                        </td>
                        <td>@item.Password</td>
                        <td>
                            <a asp-action="Approve" asp-route-id="@item.ID" class="btn btn-success">Approve</a>
                             <a asp-action="Reject" asp-route-id="@item.ID" class="btn btn-danger">Reject</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

BlogProject.WEB/Areas/Admin/Views/AppUser/Detail.cshtml
@model GetAppUserProfileVM


<div class="row mt-2">

    <!-- AppUser Article List -->
    <div class="col-md-9">
        <hr />
        @foreach (var item in @Model.Articles.OrderByDescending(a => a.CreateDate))
        {
            <!--Article List-->
            <div>
                <div class="row">
                    <!-- Article Title - Content -->
                <div class="col-md-10 pe-2">

                        @if (@item.Title.Length > 100)
                        {
                            <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ID" class="fw-bold text-dark">
                                <h5 class="mt-2"><strong>@item.Title.Substring(0,100)</strong></h5>
                            </a>
                        }
                        else
                        {
                            <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ID" class="fw-bold text-dark">
                                <h5 class="mt-2"><strong>@item.Title</strong></h5>
                            </a>

                        }


                        @if (@item.Content.Length > 250)
                        {
                            <p class="mb-1">
                                @item.Content.Substring(0,250) <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ID" class="fw-bold">...</a>
                            </p>
                        }
                        else
                        {
                            <p class="mb-1">
                                @item.Content
                            </p>
                        }

                        <label class="m-2 text-muted fw-light">@item.CreateDate.ToShortDateString() / @item.ReadingTime - min read / @item.ReadCounter times read </label>
                        <br>

                        <a asp-action="ListWithFilter" asp-controller="Article" asp-route-id="@item.CategoryID" class="btn btn-secondary btn-sm fw-info px-2 py-1">@item.Category.Name</a>

                    </div>

                    <!-- Article Image -->
                <div class="col-md-2 d-flex justify-content-end">

                        <img class="mt-3" src="@item.Image" style="height:120px;width:120px" />

                    </div>
                </div>
            </div>
            <hr />
        }

    </div>

    <!-- Followed Category and Information Div -->
    <div class="col-md-2 ms-5" style="border-left: medium solid grey">
        <div class="row sticky-top ms-3">
            <div class="mt-4">
                <div>
                    <img class="rounded-circle" src="@Model.Image" style="height:100px;width:100px" />
                </div>

                <h6 class="mt-4 fw-bold">@Model.FullName</h6>
                <p class="text-muted fw-normal fst-italic">@Model.Mail</p>

                <p class="mt-4 p-0 fw-bold" style="border-bottom: thin solid grey">Following Categories</p>


                @foreach (var item in @Model.Categories)
                {
                    <div class="mb-2">
                        <a class="mb-2 text-dark " asp-action="ListWithFilter" asp-controller="Article" asp-route-id="@item.ID">@item.Name</a>
                    </div>
                }


            </div>
            <!-- Profile Picture -->


        </div>

    </div>
</div>

BlogProject.WEB/Areas/Admin/Views/AppUser/Index.cshtml
@model List<GetArticleWithUserVM>


<div class="row mt-2">

    <!-- AppUser Article List -->
    <div class="col-md-9">
        <hr />
        @foreach (var item in @Model)
        {
            <!-- Irformation Header -->
            <div class="row mt-2">

                <!-- Writer Profile Pic-->
            <div class="col-md-1 px-0 ms-2 p-0">
                    <img class="rounded-circle p-0" src="@item.UserImage" style="height:55px;width:50px" />
                </div>

                <!-- Information Detail -->
            <div class="col-md-10">
                    <!-- Writer FullName -->
                <div class="">
                        <a class="text-dark fw-bold" asp-controller="AppUser" asp-action="Detail" asp-route-id="@item.UserId">@item.UserFullName </a>
                    </div>
                    <!--Create Date - Reading Time-->
                <div>
                        <label class="text-muted fw-light">@item.CreateDate.ToShortDateString() / @item.ReadingTime - min read / @item.ReadCounter times read </label>
                    </div>
                </div>

            </div>
            <!--Article List-->
            <div>
                <div class="row">
                    <!-- Article Title - Content -->
                <div class="col-md-9 pe-2">

                        @if (@item.Title.Length > 100)
                        {
                            <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ArticleId" class="fw-bold text-dark">
                                <h5 class="mt-2"><strong>@item.Title.Substring(0,100)</strong></h5>
                            </a>
                        }
                        else
                        {
                            <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ArticleId" class="fw-bold text-dark">
                                <h5 class="mt-2"><strong>@item.Title</strong></h5>
                            </a>

                        }


                        @if (@item.Content.Length > 250)
                        {
                            <p class="mb-1">
                                @item.Content.Substring(0,250) <a asp-action="Detail" asp-controller="Article" asp-route-id="@item.ArticleId" class="fw-bold">...</a>
                            </p>
                        }
                        else
                        {
                            <p class="mb-1">
                                @item.Content
                            </p>
                        }

                        <!--Article Category-->
                    <a asp-action="ListWithFilter" asp-controller="Article" asp-route-id="@item.CategoryID" class="btn btn-secondary btn-sm fw-info px-2 py-1">@item.CategoryName</a>


                    </div>

                    <!-- Article Image -->
                <div class="col-md-2 d-flex justify-content-end">

                        <img class="mt-3" src="@item.Image" style="height:120px;width:120px" />

                    </div>
                </div>
            </div>
            <hr />
        }

    </div>

    <!-- Followed Category and Information Div -->
    <div class="col-md-2 ms-5" style="border-left: medium solid grey">
        <div class="row sticky-top ms-3">
            <div class="mt-4">


                <p class="mt-4 p-0 fw-bold" style="border-bottom: thin solid grey">Followable Categories</p>

                <form asp-controller="Article" asp-action="ListWithFilters" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="All"></div>
                    <div class="mb-2">
                        <button type="submit" class="btn btn-success">Filters</button>
                        <hr />
                    </div>

                    @foreach (var item in @ViewBag.AllCategory)
                    {
                        <div class="mb-2">
                            <input type="checkbox" class="btn-check" name="categories[]" value="@item.ID" id="@item.ID" autocomplete="off">
                            <label class="btn btn-outline-primary" for="@item.ID">@item.Name</label>
                            <br>
                        </div>
                    }
                </form>


            </div>
            <!-- Profile Picture -->


        </div>

    </div>
</div>

BlogProject.WEB/Areas/Admin/Views/AppUser/List.cshtml
@model List<AppUser>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Users</h3>
        <div class="card-tools">
            <ul class="pagination pagination-sm float-right">
                <li class="page-item"><a class="page-link" href="#">«</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">»</a></li>
            </ul>
        </div>
    </div>

    <div class="card-body p-0">
        <table class="table">

            <!-- Table Head -->
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>FullName</th>
                    <th>UserName</th>
                    <th>E-Mail</th>
                    <th>Password</th>
                    <th style="width: 200px" class="text-center">Operations</th>
                </tr>
            </thead>

            <!-- Table Body -->
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><img src="@item.Image" class="img-circle" style="width: 50px" /></td>
                  <td> <a class="text-dark" asp-controller="AppUser" asp-action="Detail" asp-route-id="@item.ID">@item.FullName</a></td>
                        <td>@item.UserName</td>
                        <td>
                            @foreach (var users in ViewBag.MailList)
                            {
                                @if (users.Id==item.IdentityId)
                                {
                                    @users.Email
                                }
                            }
                        </td>
                        <td>@item.Password</td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">Delete</a>
                             <a asp-action="Detail" asp-route-id="@item.ID" class="btn btn-secondary">Detail</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>